### ISSUE TITLE
Running code2flow on chipscopy library causes crash. 

### ISSUE THREAD

**Issue by outputlogic** [scottrogowski/code2flow#42]
Running code2flow on chipscopy library causes crash. The library is stable and fully functional.
Library location:
  https://github.com/Xilinx/chipscopy/tree/master/chipscopy
Command: code2flow -v C:\chipscopy
Python rev: 3.9.5
Operating system: Windows 10

Traceback (most recent call last):
  File "C:\Python39\Scripts\code2flow-script.py", line 33, in <module>
    sys.exit(load_entry_point('code2flow==2.3.0', 'console_scripts', 'code2flow')())
  File "C:\Python39\lib\site-packages\code2flow\engine.py", line 630, in main
    code2flow(
  File "C:\Python39\lib\site-packages\code2flow\engine.py", line 536, in code2flow
    file_groups, all_nodes, edges = map_it(sources, language, no_trimming,
  File "C:\Python39\lib\site-packages\code2flow\engine.py", line 324, in map_it
    file_group = make_file_group(file_ast_tree, source, extension)
  File "C:\Python39\lib\site-packages\code2flow\engine.py", line 208, in make_file_group
    file_group.add_node(language.make_root_node(body_trees, parent=file_group), is_root=True)
  File "C:\Python39\lib\site-packages\code2flow\python.py", line 229, in make_root_node
    variables = make_local_variables(lines, parent)
  File "C:\Python39\lib\site-packages\code2flow\python.py", line 122, in make_local_variables
    variables += process_import(element)
  File "C:\Python39\lib\site-packages\code2flow\python.py", line 99, in process_import
    rhs = djoin(element.module, rhs)
  File "C:\Python39\lib\site-packages\code2flow\model.py", line 51, in djoin
    return '.'.join(tup)
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by scottrogowski** [comment]
Someone else ran into a similar issue yesterday. It might be the same. Will investigate. Thank you for submitting!

**Comment by scottrogowski** [comment]
I believe you ran into an issue that got fixed in 2.3.1. At least, the chipscopy repo processed for me when using that new release. There is a tiny chance your issue is windows specific so if you continue to have problems, feel free to reopen.
