### ISSUE TITLE
Bug: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by andheiberg-babylonhealth** [scottrogowski/code2flow#43]
Trying to create the graph for a moderate size rails pp gives me:

```
$ code2flow --language=rb --ruby-version 27 app/**/*.rb

...

Traceback (most recent call last):
  File "/usr/local/bin/code2flow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/code2flow/engine.py", line 630, in main
    code2flow(
  File "/usr/local/lib/python3.9/site-packages/code2flow/engine.py", line 536, in code2flow
    file_groups, all_nodes, edges = map_it(sources, language, no_trimming,
  File "/usr/local/lib/python3.9/site-packages/code2flow/engine.py", line 346, in map_it
    subgroup.inherits = [nodes_by_subgroup_token.get(g) for g in subgroup.inherits]
  File "/usr/local/lib/python3.9/site-packages/code2flow/engine.py", line 346, in <listcomp>
    subgroup.inherits = [nodes_by_subgroup_token.get(g) for g in subgroup.inherits]
TypeError: unhashable type: 'list'
```

**Comment by scottrogowski** [comment]
Hi, this is likely a real bug. Could you share the source or a portion of the source so that I can reproduce?

**Comment by scottrogowski** [comment]
Closing for inactivity. Please reopen if still an issue.

**Comment by andheiberg-babylonhealth** [comment]
Sorry sadly I can't share the source for this project.
