### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ahamid** [scottrogowski/code2flow#8]
I am running this on a ~1.2mb 38kloc browserified source file, and it's been running for > 10 mins at 100% cpu on a core i7.  no disk output, and no output from `strace` so it appears internally cpu bound.  a note of advisement as to the applicability to project size would probably be helpful.

Update: Traceback when I Ctrl-C it is:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.9/bin/code2flow", line 4, in <module>
    __import__('pkg_resources').run_script('code2flow==0.2', 'code2flow')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 723, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1643, in run_script
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/code2flow-0.2-py2.7.egg/EGG-INFO/scripts/code2flow", line 151, in <module>

  File "build/bdist.linux-x86_64/egg/code2flowlib/engine.py", line 810, in map
  File "build/bdist.linux-x86_64/egg/code2flowlib/engine.py", line 369, in __init__
  File "build/bdist.linux-x86_64/egg/code2flowlib/engine.py", line 721, in _removeCommentsAndStrings
```

Update 2: the original source file had (believe it or not) >2mb of sourceMap (a single massive line) appended to it.  Once I removed it, code2flow did complete after several minutes, so perhaps there is a pathological case in extremely long comment.

**Comment by scottrogowski** [comment]
Thanks for the feedback. I'll do some testing and try to establish where
performance starts to degrade

**Comment by ahamid** [comment]
As an aside it appears browserify totally confounds code2flow although I can't fault it, it's probably because everything is pulled in essentially by dynamic require lookups.

**Comment by scottrogowski** [comment]
I'm not surprised. Code2flow is not going to work in all cases and it's output needs to be taken with a grain of salt. I'm planning to work on some updates to it in the next few weeks and I may try to address browserify.

**Comment by scottrogowski** [comment]
Hi all. Code2flow has been rewritten and I suspect that performance will no longer be an issue. Sorry for the 6 year delay :)
